name: emnist-api
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - python-multipart
      - pillow
      - numpy
      - scipy
      - matplotlib
      - tensorflow
      - streamlit
      - streamlit-drawable-canvas
      - requests